name: PuzzleAvatar
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - pip
  - python=3.10
  - pytorch=2.3.1
  - pytorch-cuda=12.1
  - torchvision=0.20.1
  - pip:
    - tqdm
    - accelerate
    - albumentations
    - boto3
    - chumpy
    - dataclasses
    - dearpygui
    - diffusers
    - einops
    - imageio-ffmpeg
    - imageio
    - kornia
    - lpips
    - matplotlib
    - mediapipe
    - ninja
    - omegaconf
    - open3d
    - opencv_contrib_python
    - opencv-python
    - packaging
    - protobuf
    - pudb
    - pyfqmr
    - PyMCubes
    - pymeshfix
    - pymeshlab
    - PyOpenGL
    - pyrender
    - pyrr
    - pytorch-lightning==2.1.0
    - pyvista
    - replicate
    - rich
    - rtree
    - scikit-image
    - scikit-learn
    - streamlit
    - tensorboardX
    - test-tube
    - tetgen
    - torch-ema
    - torch-fidelity
    - torchmetrics
    - transformers
    - trimesh
    - xatlas
    - yapf
    - autoflake
    - datasets
    - cchardet
    - chardet
    - openai
    - func_timeout
    - ultralytics
    - sentencepiece
    - deepspeed
    - flash_attn
    - openpyxl
    - xformers
    - face_alignment
    - rectangle-packer
    - wandb
    - mesh-to-sdf
    - segment_anything
    - face_alignment
    - mediapipe
    - pillow
    - bitsandbytes
